{
  "formatVersion": "1.1",
  "component": {
    "group": "com.retiredroca.mcstorageareanetwork",
    "module": "mc_storage_area_network-neoforge-1.21.1",
    "version": "1.0.26091502",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mc_storage_area_network-neoforge-1.21.1-1.0.26091502.jar",
          "url": "mc_storage_area_network-neoforge-1.21.1-1.0.26091502.jar",
          "size": 36909,
          "sha512": "114a1d3bc4792653c7c2100ebe78df4272c24239c73fd0e0ce7adf3fae9d26ed37a68dc5f101cd102d47b2c7c4a8d768b42611f73c9c98bc2a7924f97c7a2751",
          "sha256": "b4cfdab7775d9f18dcdd1426e5c5600b9d108ffb9617ae69ecc1d7cb6e50bef1",
          "sha1": "9666c585fee18f59a6ed52d3556b507be1e4e323",
          "md5": "8fd9de08b7d3f0d7b30afaa58b90ecb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mc_storage_area_network-neoforge-1.21.1-1.0.26091502.jar",
          "url": "mc_storage_area_network-neoforge-1.21.1-1.0.26091502.jar",
          "size": 36909,
          "sha512": "114a1d3bc4792653c7c2100ebe78df4272c24239c73fd0e0ce7adf3fae9d26ed37a68dc5f101cd102d47b2c7c4a8d768b42611f73c9c98bc2a7924f97c7a2751",
          "sha256": "b4cfdab7775d9f18dcdd1426e5c5600b9d108ffb9617ae69ecc1d7cb6e50bef1",
          "sha1": "9666c585fee18f59a6ed52d3556b507be1e4e323",
          "md5": "8fd9de08b7d3f0d7b30afaa58b90ecb2"
        }
      ]
    }
  ]
}
