{
  "formatVersion": "1.1",
  "component": {
    "group": "com.retiredroca.mcstorageareanetwork",
    "module": "mc_storage_area_network-neoforge",
    "version": "1.0.26091413",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mc_storage_area_network-neoforge-1.0.26091413.jar",
          "url": "mc_storage_area_network-neoforge-1.0.26091413.jar",
          "size": 34333,
          "sha512": "2b477d2e5516bfd615f36ae78c9d12d732c8950c2df53ff5712cd97ce79ee5c71bd8dd65c88fb5f720269201b91ce4ac80cf31b9a8fb347fc57bb92f0da47a04",
          "sha256": "a098c23cef015e7c75baa02d18d37f780e0432ea031b2c382b20e0f245146de8",
          "sha1": "50efe36e3cc8195b5890e958cf591cd5d7ecf0be",
          "md5": "27c4a23b6525f81a45ce7a662e9aef9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mc_storage_area_network-neoforge-1.0.26091413.jar",
          "url": "mc_storage_area_network-neoforge-1.0.26091413.jar",
          "size": 34333,
          "sha512": "2b477d2e5516bfd615f36ae78c9d12d732c8950c2df53ff5712cd97ce79ee5c71bd8dd65c88fb5f720269201b91ce4ac80cf31b9a8fb347fc57bb92f0da47a04",
          "sha256": "a098c23cef015e7c75baa02d18d37f780e0432ea031b2c382b20e0f245146de8",
          "sha1": "50efe36e3cc8195b5890e958cf591cd5d7ecf0be",
          "md5": "27c4a23b6525f81a45ce7a662e9aef9b"
        }
      ]
    }
  ]
}
