{
  "formatVersion": "1.1",
  "component": {
    "group": "com.retiredroca.mcstorageareanetwork",
    "module": "mc_storage_area_network-neoforge-1.21.1",
    "version": "1.0.2.26091512",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mc_storage_area_network-neoforge-1.21.1-1.0.2.26091512.jar",
          "url": "mc_storage_area_network-neoforge-1.21.1-1.0.2.26091512.jar",
          "size": 45905,
          "sha512": "57f29e36e06bd627950db578ab2d00e6c52611a098ce905959fe8759aba55eb0a1f03810485ba0b57d6ebdb047a991bd384a24510e2f6e2f500b3843abac097d",
          "sha256": "04c0d8216eff6259b8226e45bdcbad1a9224f90fe07878a789f9a87df986c8c9",
          "sha1": "decc23032b5a6e18005a45ddd55b666a756053bd",
          "md5": "18285942a43cb929bf33bd4d05548789"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mc_storage_area_network-neoforge-1.21.1-1.0.2.26091512.jar",
          "url": "mc_storage_area_network-neoforge-1.21.1-1.0.2.26091512.jar",
          "size": 45905,
          "sha512": "57f29e36e06bd627950db578ab2d00e6c52611a098ce905959fe8759aba55eb0a1f03810485ba0b57d6ebdb047a991bd384a24510e2f6e2f500b3843abac097d",
          "sha256": "04c0d8216eff6259b8226e45bdcbad1a9224f90fe07878a789f9a87df986c8c9",
          "sha1": "decc23032b5a6e18005a45ddd55b666a756053bd",
          "md5": "18285942a43cb929bf33bd4d05548789"
        }
      ]
    }
  ]
}
