{
  "formatVersion": "1.1",
  "component": {
    "group": "com.retiredroca.mcstorageareanetwork",
    "module": "mc_storage_area_network-neoforge-1.21.1",
    "version": "1.0.2.26091512",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mc_storage_area_network-neoforge-1.21.1-1.0.2.26091512.jar",
          "url": "mc_storage_area_network-neoforge-1.21.1-1.0.2.26091512.jar",
          "size": 54817,
          "sha512": "adba7d0cd94c5991225a1a8801a75e342fd82c90b6c8dffd9a44832fe147dcdee06716cc46bad562a11edf88316e39a9ba7191c47c4127f585b4db8aca7fdbf7",
          "sha256": "a25aea924a285c83e82e3fac8f3b0e8acc9c8a6146364b5438bdea96bc11b67b",
          "sha1": "4a9126f06efa263fd661b6001dbc1c2156bce273",
          "md5": "b12c4fc701ff4cbbe2b3975e53ba8861"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mc_storage_area_network-neoforge-1.21.1-1.0.2.26091512.jar",
          "url": "mc_storage_area_network-neoforge-1.21.1-1.0.2.26091512.jar",
          "size": 54817,
          "sha512": "adba7d0cd94c5991225a1a8801a75e342fd82c90b6c8dffd9a44832fe147dcdee06716cc46bad562a11edf88316e39a9ba7191c47c4127f585b4db8aca7fdbf7",
          "sha256": "a25aea924a285c83e82e3fac8f3b0e8acc9c8a6146364b5438bdea96bc11b67b",
          "sha1": "4a9126f06efa263fd661b6001dbc1c2156bce273",
          "md5": "b12c4fc701ff4cbbe2b3975e53ba8861"
        }
      ]
    }
  ]
}
