{
  "formatVersion": "1.1",
  "component": {
    "group": "com.retiredroca.itemnetwork",
    "module": "item_network_api-neoforge",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "item_network_api-neoforge-1.0.0.jar",
          "url": "item_network_api-neoforge-1.0.0.jar",
          "size": 26301,
          "sha512": "67bf02d564625a9f0a9257a53d65c616e03f1f3dafe1f726c039ef0d29499691efd69ce7f0360498a632e8cc7787347dfecc5f7aedcf057803661c40d4e489d0",
          "sha256": "f6ad2a36bad93470611860483d215cb68754547270877f16afec1a15a4762f32",
          "sha1": "73055b4817b1e30574dc7650a3ee66a3ca68e513",
          "md5": "36b2f2b8c15dfa0d6107913023bd3288"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "item_network_api-neoforge-1.0.0.jar",
          "url": "item_network_api-neoforge-1.0.0.jar",
          "size": 26301,
          "sha512": "67bf02d564625a9f0a9257a53d65c616e03f1f3dafe1f726c039ef0d29499691efd69ce7f0360498a632e8cc7787347dfecc5f7aedcf057803661c40d4e489d0",
          "sha256": "f6ad2a36bad93470611860483d215cb68754547270877f16afec1a15a4762f32",
          "sha1": "73055b4817b1e30574dc7650a3ee66a3ca68e513",
          "md5": "36b2f2b8c15dfa0d6107913023bd3288"
        }
      ]
    }
  ]
}
