{
  "formatVersion": "1.1",
  "component": {
    "group": "com.retiredroca.mcstorageareanetwork",
    "module": "mc_storage_area_network-neoforge-1.21.1",
    "version": "1.0.2.26091618",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mc_storage_area_network-neoforge-1.21.1-1.0.2.26091618.jar",
          "url": "mc_storage_area_network-neoforge-1.21.1-1.0.2.26091618.jar",
          "size": 89619,
          "sha512": "780133e0b5151ee1ca9ba0411329e429881936e8f382b7f9de5c94eefffd841e01eb2595b5627414d2264defc63f2a1b83baab23ce91fe302aeb7175f1d59d2c",
          "sha256": "412f2fbff55ec32492eff22ef90d02a04c6065c7084b7b118f92822cee86cfbd",
          "sha1": "9408b996f5d195844fee8f43ad1afb29042f3882",
          "md5": "d6c6c5731b862943840e4f0c352ed04f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mc_storage_area_network-neoforge-1.21.1-1.0.2.26091618.jar",
          "url": "mc_storage_area_network-neoforge-1.21.1-1.0.2.26091618.jar",
          "size": 89619,
          "sha512": "780133e0b5151ee1ca9ba0411329e429881936e8f382b7f9de5c94eefffd841e01eb2595b5627414d2264defc63f2a1b83baab23ce91fe302aeb7175f1d59d2c",
          "sha256": "412f2fbff55ec32492eff22ef90d02a04c6065c7084b7b118f92822cee86cfbd",
          "sha1": "9408b996f5d195844fee8f43ad1afb29042f3882",
          "md5": "d6c6c5731b862943840e4f0c352ed04f"
        }
      ]
    }
  ]
}
