{
  "formatVersion": "1.1",
  "component": {
    "group": "com.retiredroca.mcstorageareanetwork",
    "module": "mc_storage_area_network-neoforge-1.21.1",
    "version": "1.0.2.26091618",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mc_storage_area_network-neoforge-1.21.1-1.0.2.26091618.jar",
          "url": "mc_storage_area_network-neoforge-1.21.1-1.0.2.26091618.jar",
          "size": 89619,
          "sha512": "e9526befde0e665e38c6196ffe87d97c6a48ce3ea4d39601c4a10149b5c62f10217ee743eda893f83bc7bcd5032a708a4e14971146142f9a59af69bff23d5629",
          "sha256": "c09c4c33ce081958c7d885f9cca5b1f4580df8b6da5af927badec28900765a29",
          "sha1": "aa268693086b4bee4db88850146daa3ed943e727",
          "md5": "0d91ffc622fc374c01abed1b87b6c5fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mc_storage_area_network-neoforge-1.21.1-1.0.2.26091618.jar",
          "url": "mc_storage_area_network-neoforge-1.21.1-1.0.2.26091618.jar",
          "size": 89619,
          "sha512": "e9526befde0e665e38c6196ffe87d97c6a48ce3ea4d39601c4a10149b5c62f10217ee743eda893f83bc7bcd5032a708a4e14971146142f9a59af69bff23d5629",
          "sha256": "c09c4c33ce081958c7d885f9cca5b1f4580df8b6da5af927badec28900765a29",
          "sha1": "aa268693086b4bee4db88850146daa3ed943e727",
          "md5": "0d91ffc622fc374c01abed1b87b6c5fc"
        }
      ]
    }
  ]
}
