{
  "formatVersion": "1.1",
  "component": {
    "group": "com.retiredroca.mcstorageareanetwork",
    "module": "mc_storage_area_network-neoforge",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mc_storage_area_network-neoforge-1.0.2.jar",
          "url": "mc_storage_area_network-neoforge-1.0.2.jar",
          "size": 34327,
          "sha512": "b518b5fd21ccc380eb0ecd1815f869cf8f77d9068c3859fb9b4b8d891a57db6b5361fe3e3dd534d5e439b17a70c13f12cbab45a55aa8591b851b3d8e027ee204",
          "sha256": "d04ee1ef1317c090da6fb1ed259e9aed5d2acb9bb3f4abb4e4719fe7e92a6017",
          "sha1": "af9d6b3302bc62a0d71de0523adebd311e2373da",
          "md5": "3b381e33950757b7162085f420339853"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mc_storage_area_network-neoforge-1.0.2.jar",
          "url": "mc_storage_area_network-neoforge-1.0.2.jar",
          "size": 34327,
          "sha512": "b518b5fd21ccc380eb0ecd1815f869cf8f77d9068c3859fb9b4b8d891a57db6b5361fe3e3dd534d5e439b17a70c13f12cbab45a55aa8591b851b3d8e027ee204",
          "sha256": "d04ee1ef1317c090da6fb1ed259e9aed5d2acb9bb3f4abb4e4719fe7e92a6017",
          "sha1": "af9d6b3302bc62a0d71de0523adebd311e2373da",
          "md5": "3b381e33950757b7162085f420339853"
        }
      ]
    }
  ]
}
