{
  "formatVersion": "1.1",
  "component": {
    "group": "com.retiredroca.mcstorageareanetwork",
    "module": "mc_storage_area_network-neoforge-1.21.1",
    "version": "1.0.26091501",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mc_storage_area_network-neoforge-1.21.1-1.0.26091501.jar",
          "url": "mc_storage_area_network-neoforge-1.21.1-1.0.26091501.jar",
          "size": 34333,
          "sha512": "0a6d6cddb532f9160013b77efc3271a3a97087817c5c8360b6e94e8e05d38a500fccc7b23da3b7cddcc9fd90980559e4085defefa4829d8052dbe8158fc4c5f8",
          "sha256": "7c3eb32b7d724bdcf7223da54f37f06e5d2191e861209e43cd350dfe5a585427",
          "sha1": "8f12da01d5ad8013e90134a49e8682b37400067d",
          "md5": "703dcdf2a3098d231ba796fb664f3f39"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mc_storage_area_network-neoforge-1.21.1-1.0.26091501.jar",
          "url": "mc_storage_area_network-neoforge-1.21.1-1.0.26091501.jar",
          "size": 34333,
          "sha512": "0a6d6cddb532f9160013b77efc3271a3a97087817c5c8360b6e94e8e05d38a500fccc7b23da3b7cddcc9fd90980559e4085defefa4829d8052dbe8158fc4c5f8",
          "sha256": "7c3eb32b7d724bdcf7223da54f37f06e5d2191e861209e43cd350dfe5a585427",
          "sha1": "8f12da01d5ad8013e90134a49e8682b37400067d",
          "md5": "703dcdf2a3098d231ba796fb664f3f39"
        }
      ]
    }
  ]
}
