{
  "formatVersion": "1.1",
  "component": {
    "group": "com.retiredroca.mcstorageareanetwork",
    "module": "mc_storage_area_network-neoforge-1.21.1",
    "version": "1.0.26091501",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mc_storage_area_network-neoforge-1.21.1-1.0.26091501.jar",
          "url": "mc_storage_area_network-neoforge-1.21.1-1.0.26091501.jar",
          "size": 34333,
          "sha512": "3f107c2c1678becff142eeb0544b072b1ea773f8ca8f23dc12909605ea4472b22d3f88da267fded890d04b02dbe35f8c77bbddebf3b8ba2beff8b4d2943cdaca",
          "sha256": "dc6f9763498d9a98ed680a62876870549e43e9819a1e1ad9fb59060b9fce9777",
          "sha1": "64e5c5d6aa9445e2acec23c182f62eca5e9e6e2c",
          "md5": "29f1519a70ef562b70e78077f5977468"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mc_storage_area_network-neoforge-1.21.1-1.0.26091501.jar",
          "url": "mc_storage_area_network-neoforge-1.21.1-1.0.26091501.jar",
          "size": 34333,
          "sha512": "3f107c2c1678becff142eeb0544b072b1ea773f8ca8f23dc12909605ea4472b22d3f88da267fded890d04b02dbe35f8c77bbddebf3b8ba2beff8b4d2943cdaca",
          "sha256": "dc6f9763498d9a98ed680a62876870549e43e9819a1e1ad9fb59060b9fce9777",
          "sha1": "64e5c5d6aa9445e2acec23c182f62eca5e9e6e2c",
          "md5": "29f1519a70ef562b70e78077f5977468"
        }
      ]
    }
  ]
}
