{
  "formatVersion": "1.1",
  "component": {
    "group": "com.retiredroca.itemnetwork",
    "module": "item_network_api-neoforge",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "item_network_api-neoforge-1.0.1.jar",
          "url": "item_network_api-neoforge-1.0.1.jar",
          "size": 26375,
          "sha512": "0e2bfdaac5659024a00cbbe7b04b3e204cb0018a554c7e3921abce8610e607cbe8cfe2cc8fd83d93bfc39ecce94153f816ff45404d5e118f20d50a0b0738f1af",
          "sha256": "bbbccd5dc023a87769f7450045c19ac0e5dc2f5e9548c442947cd6f8487512a1",
          "sha1": "12fa7f3c2181e0573fb976af108994db7e045b02",
          "md5": "810af13f65cafbf4f1dd3ef97912a603"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "item_network_api-neoforge-1.0.1.jar",
          "url": "item_network_api-neoforge-1.0.1.jar",
          "size": 26375,
          "sha512": "0e2bfdaac5659024a00cbbe7b04b3e204cb0018a554c7e3921abce8610e607cbe8cfe2cc8fd83d93bfc39ecce94153f816ff45404d5e118f20d50a0b0738f1af",
          "sha256": "bbbccd5dc023a87769f7450045c19ac0e5dc2f5e9548c442947cd6f8487512a1",
          "sha1": "12fa7f3c2181e0573fb976af108994db7e045b02",
          "md5": "810af13f65cafbf4f1dd3ef97912a603"
        }
      ]
    }
  ]
}
