{
  "formatVersion": "1.1",
  "component": {
    "group": "com.retiredroca.mcstorageareanetwork",
    "module": "mc_storage_area_network-neoforge-1.21.1",
    "version": "1.0.2.26091603",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mc_storage_area_network-neoforge-1.21.1-1.0.2.26091603.jar",
          "url": "mc_storage_area_network-neoforge-1.21.1-1.0.2.26091603.jar",
          "size": 89619,
          "sha512": "4bf854faf298e0271a90caa2cb9fa4b1b2ecc6a4e80d11b15aa43c705294af225d08b6bcc23bd3ab08f80852f863b7ca8655720d6697e9aa13a7c5285fdab3f9",
          "sha256": "bac9186ff507eaedc72ade9c6e4e737a6f6c435a8ee0160f7b75eaee7a02245d",
          "sha1": "bde9297b44b24e351e589390fca13164baff53fd",
          "md5": "a82b9496d02d6b8f4c3bf74ed34df825"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mc_storage_area_network-neoforge-1.21.1-1.0.2.26091603.jar",
          "url": "mc_storage_area_network-neoforge-1.21.1-1.0.2.26091603.jar",
          "size": 89619,
          "sha512": "4bf854faf298e0271a90caa2cb9fa4b1b2ecc6a4e80d11b15aa43c705294af225d08b6bcc23bd3ab08f80852f863b7ca8655720d6697e9aa13a7c5285fdab3f9",
          "sha256": "bac9186ff507eaedc72ade9c6e4e737a6f6c435a8ee0160f7b75eaee7a02245d",
          "sha1": "bde9297b44b24e351e589390fca13164baff53fd",
          "md5": "a82b9496d02d6b8f4c3bf74ed34df825"
        }
      ]
    }
  ]
}
